name: Mirror to GitLab

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Mirror to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/7a6172/caasi.git"
          git push --force gitlab 'refs/heads/*:refs/heads/*'
          git push --force gitlab 'refs/tags/*:refs/tags/*'